apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-charges-model-deployment
  labels:
    app: insurance-charges-model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insurance-charges-model
  template:
    metadata:
      labels:
        app: insurance-charges-model
    spec:
      containers:
        - name: insurance-charges-model
          image: registry.digitalocean.com/model-services-registry/insurance_charges_model:0.1.0
          ports:
          - containerPort: 80
            protocol: TCP
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "250m"