apiVersion: v1
kind: Service
metadata:
  name: insurance-charges-model-service
spec:
  type: LoadBalancer
  selector:
    app: insurance-charges-model
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80